export const VALIDAR_USUARIO = "VALIDAR_USUARIO";
export const REGISTRAR_USUARIO = "REGISTRAR_USUARIO";
export const GET_USUARIO = "GET_USUARIOS";
export const GET_AVATAR = "GET_AVATAR";
export  const ERROR_VALIDAION = "ERROR_VALIDAION";

export const GET_PRODUCT = "GET_PRODUCT";

export const ADD_PRODUCT_CAR = "ADD_PRODUCT_CAR"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"

export const OBTENER_USERS = "OBTENER_USERS"